// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ActivateSystem } from "../../systems/ActivateSystem.sol";
import { EntityId } from "../../types/EntityId.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type ActivateSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "ActivateSystem" }))
ActivateSystemType constant activateSystem = ActivateSystemType.wrap(
  0x73790000000000000000000000000000416374697661746553797374656d0000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title ActivateSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library ActivateSystemLib {
  error ActivateSystemLib_CallingFromRootSystem();

  function activate(ActivateSystemType self, EntityId entityId) internal {
    return CallWrapper(self.toResourceId(), address(0)).activate(entityId);
  }

  function activatePlayer(ActivateSystemType self, address playerAddress) internal {
    return CallWrapper(self.toResourceId(), address(0)).activatePlayer(playerAddress);
  }

  function activate(CallWrapper memory self, EntityId entityId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ActivateSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_activate_EntityId.activate, (entityId));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function activatePlayer(CallWrapper memory self, address playerAddress) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ActivateSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_activatePlayer_address.activatePlayer, (playerAddress));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function activate(RootCallWrapper memory self, EntityId entityId) internal {
    bytes memory systemCall = abi.encodeCall(_activate_EntityId.activate, (entityId));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function activatePlayer(RootCallWrapper memory self, address playerAddress) internal {
    bytes memory systemCall = abi.encodeCall(_activatePlayer_address.activatePlayer, (playerAddress));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(ActivateSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(ActivateSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(ActivateSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(ActivateSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(ActivateSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (ActivateSystemType) {
    return ActivateSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(ActivateSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _activate_EntityId {
  function activate(EntityId entityId) external;
}

interface _activatePlayer_address {
  function activatePlayer(address playerAddress) external;
}

using ActivateSystemLib for ActivateSystemType global;
using ActivateSystemLib for CallWrapper global;
using ActivateSystemLib for RootCallWrapper global;
