// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { BedSystem } from "../../systems/BedSystem.sol";
import { EntityId } from "../../EntityId.sol";
import { Vec3 } from "../../Vec3.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type BedSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "BedSystem" }))
BedSystemType constant bedSystem = BedSystemType.wrap(
  0x7379000000000000000000000000000042656453797374656d00000000000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title BedSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library BedSystemLib {
  error BedSystemLib_CallingFromRootSystem();

  function sleep(BedSystemType self, EntityId caller, EntityId bed, bytes memory extraData) internal {
    return CallWrapper(self.toResourceId(), address(0)).sleep(caller, bed, extraData);
  }

  function wakeup(BedSystemType self, EntityId caller, Vec3 spawnCoord, bytes memory extraData) internal {
    return CallWrapper(self.toResourceId(), address(0)).wakeup(caller, spawnCoord, extraData);
  }

  function removeDeadPlayerFromBed(BedSystemType self, EntityId player, Vec3 dropCoord) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeDeadPlayerFromBed(player, dropCoord);
  }

  function sleep(CallWrapper memory self, EntityId caller, EntityId bed, bytes memory extraData) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert BedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_sleep_EntityId_EntityId_bytes.sleep, (caller, bed, extraData));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function wakeup(CallWrapper memory self, EntityId caller, Vec3 spawnCoord, bytes memory extraData) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert BedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_wakeup_EntityId_Vec3_bytes.wakeup, (caller, spawnCoord, extraData));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeDeadPlayerFromBed(CallWrapper memory self, EntityId player, Vec3 dropCoord) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert BedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _removeDeadPlayerFromBed_EntityId_Vec3.removeDeadPlayerFromBed,
      (player, dropCoord)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function sleep(RootCallWrapper memory self, EntityId caller, EntityId bed, bytes memory extraData) internal {
    bytes memory systemCall = abi.encodeCall(_sleep_EntityId_EntityId_bytes.sleep, (caller, bed, extraData));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function wakeup(RootCallWrapper memory self, EntityId caller, Vec3 spawnCoord, bytes memory extraData) internal {
    bytes memory systemCall = abi.encodeCall(_wakeup_EntityId_Vec3_bytes.wakeup, (caller, spawnCoord, extraData));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeDeadPlayerFromBed(RootCallWrapper memory self, EntityId player, Vec3 dropCoord) internal {
    bytes memory systemCall = abi.encodeCall(
      _removeDeadPlayerFromBed_EntityId_Vec3.removeDeadPlayerFromBed,
      (player, dropCoord)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(BedSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(BedSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(BedSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(BedSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(BedSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (BedSystemType) {
    return BedSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(BedSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _sleep_EntityId_EntityId_bytes {
  function sleep(EntityId caller, EntityId bed, bytes memory extraData) external;
}

interface _wakeup_EntityId_Vec3_bytes {
  function wakeup(EntityId caller, Vec3 spawnCoord, bytes memory extraData) external;
}

interface _removeDeadPlayerFromBed_EntityId_Vec3 {
  function removeDeadPlayerFromBed(EntityId player, Vec3 dropCoord) external;
}

using BedSystemLib for BedSystemType global;
using BedSystemLib for CallWrapper global;
using BedSystemLib for RootCallWrapper global;
