// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CraftFuelSystem } from "../../systems/CraftFuelSystem.sol";
import { EntityId } from "../../EntityId.sol";
import { SlotAmount } from "../../utils/InventoryUtils.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type CraftFuelSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "CraftFuelSystem" }))
CraftFuelSystemType constant craftFuelSystem = CraftFuelSystemType.wrap(
  0x7379000000000000000000000000000043726166744675656c53797374656d00
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title CraftFuelSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library CraftFuelSystemLib {
  error CraftFuelSystemLib_CallingFromRootSystem();

  function craftFuel(
    CraftFuelSystemType self,
    EntityId caller,
    EntityId powerstone,
    SlotAmount[] memory inputs
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).craftFuel(caller, powerstone, inputs);
  }

  function craftFuel(
    CallWrapper memory self,
    EntityId caller,
    EntityId powerstone,
    SlotAmount[] memory inputs
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CraftFuelSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _craftFuel_EntityId_EntityId_SlotAmountArray.craftFuel,
      (caller, powerstone, inputs)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function craftFuel(
    RootCallWrapper memory self,
    EntityId caller,
    EntityId powerstone,
    SlotAmount[] memory inputs
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _craftFuel_EntityId_EntityId_SlotAmountArray.craftFuel,
      (caller, powerstone, inputs)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(CraftFuelSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(CraftFuelSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(CraftFuelSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(CraftFuelSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(CraftFuelSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (CraftFuelSystemType) {
    return CraftFuelSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(CraftFuelSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _craftFuel_EntityId_EntityId_SlotAmountArray {
  function craftFuel(EntityId caller, EntityId powerstone, SlotAmount[] memory inputs) external;
}

using CraftFuelSystemLib for CraftFuelSystemType global;
using CraftFuelSystemLib for CallWrapper global;
using CraftFuelSystemLib for RootCallWrapper global;
