// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CraftSystem } from "../../systems/CraftSystem.sol";
import { EntityId } from "../../EntityId.sol";
import { SlotAmount } from "../../utils/InventoryUtils.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type CraftSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "CraftSystem" }))
CraftSystemType constant craftSystem = CraftSystemType.wrap(
  0x73790000000000000000000000000000437261667453797374656d0000000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title CraftSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library CraftSystemLib {
  error CraftSystemLib_CallingFromRootSystem();

  function craftWithStation(
    CraftSystemType self,
    EntityId caller,
    bytes32 recipeId,
    EntityId station,
    SlotAmount[] memory inputs
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).craftWithStation(caller, recipeId, station, inputs);
  }

  function craft(CraftSystemType self, EntityId caller, bytes32 recipeId, SlotAmount[] memory inputs) internal {
    return CallWrapper(self.toResourceId(), address(0)).craft(caller, recipeId, inputs);
  }

  function craftWithStation(
    CallWrapper memory self,
    EntityId caller,
    bytes32 recipeId,
    EntityId station,
    SlotAmount[] memory inputs
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CraftSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _craftWithStation_EntityId_bytes32_EntityId_SlotAmountArray.craftWithStation,
      (caller, recipeId, station, inputs)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function craft(CallWrapper memory self, EntityId caller, bytes32 recipeId, SlotAmount[] memory inputs) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CraftSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_craft_EntityId_bytes32_SlotAmountArray.craft, (caller, recipeId, inputs));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function craftWithStation(
    RootCallWrapper memory self,
    EntityId caller,
    bytes32 recipeId,
    EntityId station,
    SlotAmount[] memory inputs
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _craftWithStation_EntityId_bytes32_EntityId_SlotAmountArray.craftWithStation,
      (caller, recipeId, station, inputs)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function craft(RootCallWrapper memory self, EntityId caller, bytes32 recipeId, SlotAmount[] memory inputs) internal {
    bytes memory systemCall = abi.encodeCall(_craft_EntityId_bytes32_SlotAmountArray.craft, (caller, recipeId, inputs));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(CraftSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(CraftSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(CraftSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(CraftSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(CraftSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (CraftSystemType) {
    return CraftSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(CraftSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _craftWithStation_EntityId_bytes32_EntityId_SlotAmountArray {
  function craftWithStation(EntityId caller, bytes32 recipeId, EntityId station, SlotAmount[] memory inputs) external;
}

interface _craft_EntityId_bytes32_SlotAmountArray {
  function craft(EntityId caller, bytes32 recipeId, SlotAmount[] memory inputs) external;
}

using CraftSystemLib for CraftSystemType global;
using CraftSystemLib for CallWrapper global;
using CraftSystemLib for RootCallWrapper global;
