// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GuardianSystem } from "../../systems/GuardianSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type GuardianSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "GuardianSystem" }))
GuardianSystemType constant guardianSystem = GuardianSystemType.wrap(
  0x73790000000000000000000000000000477561726469616e53797374656d0000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title GuardianSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library GuardianSystemLib {
  error GuardianSystemLib_CallingFromRootSystem();

  function pause(GuardianSystemType self) internal {
    return CallWrapper(self.toResourceId(), address(0)).pause();
  }

  function unpause(GuardianSystemType self) internal {
    return CallWrapper(self.toResourceId(), address(0)).unpause();
  }

  function addGuardian(GuardianSystemType self, address guardian) internal {
    return CallWrapper(self.toResourceId(), address(0)).addGuardian(guardian);
  }

  function removeGuardian(GuardianSystemType self, address guardian) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeGuardian(guardian);
  }

  function pause(CallWrapper memory self) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert GuardianSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_pause.pause, ());
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function unpause(CallWrapper memory self) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert GuardianSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_unpause.unpause, ());
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function addGuardian(CallWrapper memory self, address guardian) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert GuardianSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_addGuardian_address.addGuardian, (guardian));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeGuardian(CallWrapper memory self, address guardian) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert GuardianSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_removeGuardian_address.removeGuardian, (guardian));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function pause(RootCallWrapper memory self) internal {
    bytes memory systemCall = abi.encodeCall(_pause.pause, ());
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function unpause(RootCallWrapper memory self) internal {
    bytes memory systemCall = abi.encodeCall(_unpause.unpause, ());
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function addGuardian(RootCallWrapper memory self, address guardian) internal {
    bytes memory systemCall = abi.encodeCall(_addGuardian_address.addGuardian, (guardian));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeGuardian(RootCallWrapper memory self, address guardian) internal {
    bytes memory systemCall = abi.encodeCall(_removeGuardian_address.removeGuardian, (guardian));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(GuardianSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(GuardianSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(GuardianSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(GuardianSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(GuardianSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (GuardianSystemType) {
    return GuardianSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(GuardianSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _pause {
  function pause() external;
}

interface _unpause {
  function unpause() external;
}

interface _addGuardian_address {
  function addGuardian(address guardian) external;
}

interface _removeGuardian_address {
  function removeGuardian(address guardian) external;
}

using GuardianSystemLib for GuardianSystemType global;
using GuardianSystemLib for CallWrapper global;
using GuardianSystemLib for RootCallWrapper global;
