// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { HitMachineSystem } from "../../systems/HitMachineSystem.sol";
import { EntityId } from "../../EntityId.sol";
import { Vec3 } from "../../Vec3.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type HitMachineSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "HitMachineSystem" }))
HitMachineSystemType constant hitMachineSystem = HitMachineSystemType.wrap(
  0x737900000000000000000000000000004869744d616368696e6553797374656d
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title HitMachineSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library HitMachineSystemLib {
  error HitMachineSystemLib_CallingFromRootSystem();

  function hitForceField(HitMachineSystemType self, EntityId caller, Vec3 coord, uint16 toolSlot) internal {
    return CallWrapper(self.toResourceId(), address(0)).hitForceField(caller, coord, toolSlot);
  }

  function hitForceField(HitMachineSystemType self, EntityId caller, Vec3 coord) internal {
    return CallWrapper(self.toResourceId(), address(0)).hitForceField(caller, coord);
  }

  function hitForceField(CallWrapper memory self, EntityId caller, Vec3 coord, uint16 toolSlot) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert HitMachineSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _hitForceField_EntityId_Vec3_uint16.hitForceField,
      (caller, coord, toolSlot)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function hitForceField(CallWrapper memory self, EntityId caller, Vec3 coord) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert HitMachineSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_hitForceField_EntityId_Vec3.hitForceField, (caller, coord));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function hitForceField(RootCallWrapper memory self, EntityId caller, Vec3 coord, uint16 toolSlot) internal {
    bytes memory systemCall = abi.encodeCall(
      _hitForceField_EntityId_Vec3_uint16.hitForceField,
      (caller, coord, toolSlot)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function hitForceField(RootCallWrapper memory self, EntityId caller, Vec3 coord) internal {
    bytes memory systemCall = abi.encodeCall(_hitForceField_EntityId_Vec3.hitForceField, (caller, coord));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(HitMachineSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(HitMachineSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(HitMachineSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(HitMachineSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(HitMachineSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (HitMachineSystemType) {
    return HitMachineSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(HitMachineSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _hitForceField_EntityId_Vec3_uint16 {
  function hitForceField(EntityId caller, Vec3 coord, uint16 toolSlot) external;
}

interface _hitForceField_EntityId_Vec3 {
  function hitForceField(EntityId caller, Vec3 coord) external;
}

using HitMachineSystemLib for HitMachineSystemType global;
using HitMachineSystemLib for CallWrapper global;
using HitMachineSystemLib for RootCallWrapper global;
