// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { HitPlayerSystem } from "../../systems/HitPlayerSystem.sol";
import { EntityId } from "../../types/EntityId.sol";
import { Vec3 } from "../../types/Vec3.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type HitPlayerSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "HitPlayerSystem" }))
HitPlayerSystemType constant hitPlayerSystem = HitPlayerSystemType.wrap(
  0x73790000000000000000000000000000486974506c6179657253797374656d00
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title HitPlayerSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library HitPlayerSystemLib {
  error HitPlayerSystemLib_CallingFromRootSystem();

  function hitPlayer(HitPlayerSystemType self, EntityId caller, Vec3 targetCoord, uint16 toolSlot) internal {
    return CallWrapper(self.toResourceId(), address(0)).hitPlayer(caller, targetCoord, toolSlot);
  }

  function hitPlayer(HitPlayerSystemType self, EntityId caller, Vec3 targetCoord) internal {
    return CallWrapper(self.toResourceId(), address(0)).hitPlayer(caller, targetCoord);
  }

  function hitPlayer(CallWrapper memory self, EntityId caller, Vec3 targetCoord, uint16 toolSlot) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert HitPlayerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _hitPlayer_EntityId_Vec3_uint16.hitPlayer,
      (caller, targetCoord, toolSlot)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function hitPlayer(CallWrapper memory self, EntityId caller, Vec3 targetCoord) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert HitPlayerSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_hitPlayer_EntityId_Vec3.hitPlayer, (caller, targetCoord));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function hitPlayer(RootCallWrapper memory self, EntityId caller, Vec3 targetCoord, uint16 toolSlot) internal {
    bytes memory systemCall = abi.encodeCall(
      _hitPlayer_EntityId_Vec3_uint16.hitPlayer,
      (caller, targetCoord, toolSlot)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function hitPlayer(RootCallWrapper memory self, EntityId caller, Vec3 targetCoord) internal {
    bytes memory systemCall = abi.encodeCall(_hitPlayer_EntityId_Vec3.hitPlayer, (caller, targetCoord));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(HitPlayerSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(HitPlayerSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(HitPlayerSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(HitPlayerSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(HitPlayerSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (HitPlayerSystemType) {
    return HitPlayerSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(HitPlayerSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _hitPlayer_EntityId_Vec3_uint16 {
  function hitPlayer(EntityId caller, Vec3 targetCoord, uint16 toolSlot) external;
}

interface _hitPlayer_EntityId_Vec3 {
  function hitPlayer(EntityId caller, Vec3 targetCoord) external;
}

using HitPlayerSystemLib for HitPlayerSystemType global;
using HitPlayerSystemLib for CallWrapper global;
using HitPlayerSystemLib for RootCallWrapper global;
