// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MachineSystem } from "../../systems/MachineSystem.sol";
import { EntityId } from "../../EntityId.sol";
import { SlotAmount } from "../../utils/InventoryUtils.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type MachineSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "MachineSystem" }))
MachineSystemType constant machineSystem = MachineSystemType.wrap(
  0x737900000000000000000000000000004d616368696e6553797374656d000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title MachineSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library MachineSystemLib {
  error MachineSystemLib_CallingFromRootSystem();

  function fuelMachine(
    MachineSystemType self,
    EntityId caller,
    EntityId machine,
    SlotAmount[] memory slots,
    bytes memory extraData
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).fuelMachine(caller, machine, slots, extraData);
  }

  function fuelMachine(
    CallWrapper memory self,
    EntityId caller,
    EntityId machine,
    SlotAmount[] memory slots,
    bytes memory extraData
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert MachineSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _fuelMachine_EntityId_EntityId_SlotAmountArray_bytes.fuelMachine,
      (caller, machine, slots, extraData)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function fuelMachine(
    RootCallWrapper memory self,
    EntityId caller,
    EntityId machine,
    SlotAmount[] memory slots,
    bytes memory extraData
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _fuelMachine_EntityId_EntityId_SlotAmountArray_bytes.fuelMachine,
      (caller, machine, slots, extraData)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(MachineSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(MachineSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(MachineSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(MachineSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(MachineSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (MachineSystemType) {
    return MachineSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(MachineSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _fuelMachine_EntityId_EntityId_SlotAmountArray_bytes {
  function fuelMachine(EntityId caller, EntityId machine, SlotAmount[] memory slots, bytes memory extraData) external;
}

using MachineSystemLib for MachineSystemType global;
using MachineSystemLib for CallWrapper global;
using MachineSystemLib for RootCallWrapper global;
