// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ModeratorSystem } from "../../systems/ModeratorSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type ModeratorSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "ModeratorSystem" }))
ModeratorSystemType constant moderatorSystem = ModeratorSystemType.wrap(
  0x737900000000000000000000000000004d6f64657261746f7253797374656d00
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title ModeratorSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library ModeratorSystemLib {
  error ModeratorSystemLib_CallingFromRootSystem();

  function pause(ModeratorSystemType self) internal {
    return CallWrapper(self.toResourceId(), address(0)).pause();
  }

  function unpause(ModeratorSystemType self) internal {
    return CallWrapper(self.toResourceId(), address(0)).unpause();
  }

  function addModerator(ModeratorSystemType self, address moderator) internal {
    return CallWrapper(self.toResourceId(), address(0)).addModerator(moderator);
  }

  function removeModerator(ModeratorSystemType self, address moderator) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeModerator(moderator);
  }

  function pause(CallWrapper memory self) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ModeratorSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_pause.pause, ());
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function unpause(CallWrapper memory self) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ModeratorSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_unpause.unpause, ());
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function addModerator(CallWrapper memory self, address moderator) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ModeratorSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_addModerator_address.addModerator, (moderator));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeModerator(CallWrapper memory self, address moderator) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ModeratorSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_removeModerator_address.removeModerator, (moderator));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function pause(RootCallWrapper memory self) internal {
    bytes memory systemCall = abi.encodeCall(_pause.pause, ());
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function unpause(RootCallWrapper memory self) internal {
    bytes memory systemCall = abi.encodeCall(_unpause.unpause, ());
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function addModerator(RootCallWrapper memory self, address moderator) internal {
    bytes memory systemCall = abi.encodeCall(_addModerator_address.addModerator, (moderator));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeModerator(RootCallWrapper memory self, address moderator) internal {
    bytes memory systemCall = abi.encodeCall(_removeModerator_address.removeModerator, (moderator));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(ModeratorSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(ModeratorSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(ModeratorSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(ModeratorSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(ModeratorSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (ModeratorSystemType) {
    return ModeratorSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(ModeratorSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _pause {
  function pause() external;
}

interface _unpause {
  function unpause() external;
}

interface _addModerator_address {
  function addModerator(address moderator) external;
}

interface _removeModerator_address {
  function removeModerator(address moderator) external;
}

using ModeratorSystemLib for ModeratorSystemType global;
using ModeratorSystemLib for CallWrapper global;
using ModeratorSystemLib for RootCallWrapper global;
