// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../types/EntityId.sol";
import { Vec3 } from "../../types/Vec3.sol";

/**
 * @title IBedSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBedSystem {
  function sleep(EntityId caller, EntityId bed, bytes calldata extraData) external;

  function wakeup(EntityId caller, Vec3 spawnCoord, bytes calldata extraData) external;

  function removeDeadPlayerFromBed(EntityId player, Vec3 dropCoord) external;
}
