// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../EntityId.sol";
import { Vec3 } from "../../Vec3.sol";
import { Direction } from "../common.sol";

/**
 * @title IBuildSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBuildSystem {
  function build(EntityId caller, Vec3 coord, uint16 slot, bytes calldata extraData) external returns (EntityId);

  function buildWithDirection(
    EntityId caller,
    Vec3 coord,
    uint16 slot,
    Direction direction,
    bytes calldata extraData
  ) external returns (EntityId);

  function jumpBuildWithDirection(
    EntityId caller,
    uint16 slot,
    Direction direction,
    bytes calldata extraData
  ) external returns (EntityId);

  function jumpBuild(EntityId caller, uint16 slot, bytes calldata extraData) external returns (EntityId);
}
