// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../EntityId.sol";
import { SlotAmount } from "../../utils/InventoryUtils.sol";

/**
 * @title ICraftFuelSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICraftFuelSystem {
  function craftFuel(EntityId caller, EntityId powerstone, SlotAmount[] memory inputs) external;
}
