// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../types/EntityId.sol";
import { SlotAmount } from "../../utils/InventoryUtils.sol";

/**
 * @title ICraftSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICraftSystem {
  function craftWithStation(EntityId caller, EntityId station, bytes32 recipeId, SlotAmount[] memory inputs) external;

  function craft(EntityId caller, bytes32 recipeId, SlotAmount[] memory inputs) external;
}
