// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../types/EntityId.sol";
import { ObjectType } from "../../types/ObjectType.sol";
import { Vec3 } from "../../types/Vec3.sol";

/**
 * @title IDebugSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDebugSystem {
  function debugAddToInventory(EntityId owner, ObjectType objectType, uint16 numObjectsToAdd) external;

  function debugAddToolToInventory(EntityId owner, ObjectType toolObjectType) external returns (EntityId);

  function debugRemoveFromInventory(EntityId owner, ObjectType objectType, uint16 numObjectsToRemove) external;

  function debugRemoveToolFromInventory(EntityId owner, EntityId tool) external;

  function debugTeleportPlayer(address playerAddress, Vec3 finalCoord) external;
}
