// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IDrandEvmnetSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDrandEvmnetSystem {
  error InvalidSignature(uint256[4] pubKey, uint256[2] message, uint256[2] signature);

  function publicKey() external pure returns (bytes memory);

  function publicKeyHash() external pure returns (bytes32);

  function genesisTimestamp() external pure returns (uint256);

  function period() external pure returns (uint256);

  function verifyBeaconRound(uint256 round, uint256[2] memory signature) external view;
}
