// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../types/EntityId.sol";
import { SlotAmount } from "../../utils/InventoryUtils.sol";

/**
 * @title IFoodSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFoodSystem {
  function eat(EntityId caller, SlotAmount memory slotAmount) external;
}
