// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Vec3 } from "../../Vec3.sol";
import { EntityId } from "../../EntityId.sol";

/**
 * @title IForceFieldSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IForceFieldSystem {
  function validateSpanningTree(
    Vec3[] memory boundary,
    uint8[] calldata boundaryIdx,
    uint8[] calldata parents
  ) external pure returns (bool);

  function computeBoundaryFragments(EntityId forceField, Vec3 fragmentCoord) external view returns (Vec3[] memory);

  function addFragment(
    EntityId caller,
    EntityId forceField,
    Vec3 refFragmentCoord,
    Vec3 fragmentCoord,
    bytes calldata extraData
  ) external;

  function removeFragment(
    EntityId caller,
    EntityId forceField,
    Vec3 fragmentCoord,
    uint8[] calldata boundaryIdx,
    uint8[] calldata parents,
    bytes calldata extraData
  ) external;
}
