// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../types/EntityId.sol";

/**
 * @title IHitPlayerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IHitPlayerSystem {
  function hitPlayer(EntityId caller, EntityId target, uint16 toolSlot, bytes calldata extraData) external;

  function hitPlayer(EntityId caller, EntityId target, bytes calldata extraData) external;
}
