// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Vec3 } from "../../types/Vec3.sol";
import { ObjectType } from "../../types/ObjectType.sol";
import { EntityId } from "../../types/EntityId.sol";

/**
 * @title IMineSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMineSystem {
  function getRandomOreType(Vec3 coord) external view returns (ObjectType);

  function mine(EntityId caller, Vec3 coord, uint16 toolSlot, bytes calldata extraData) external returns (EntityId);

  function mine(EntityId caller, Vec3 coord, bytes calldata extraData) external returns (EntityId);

  function mineUntilDestroyed(EntityId caller, Vec3 coord, uint16 toolSlot, bytes calldata extraData) external;

  function mineUntilDestroyed(EntityId caller, Vec3 coord, bytes calldata extraData) external;

  function _removeBlock(EntityId entityId, ObjectType objectType, Vec3 coord) external;
}
