// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../types/EntityId.sol";
import { Vec3 } from "../../types/Vec3.sol";
import { DrandData } from "../../utils/DrandUtils.sol";
import { ObjectType } from "../../types/ObjectType.sol";

/**
 * @title INatureSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface INatureSystem {
  function initChunkCommit(EntityId caller, Vec3 chunkCoord) external;

  function fulfillChunkCommit(Vec3 chunkCoord, DrandData calldata drand) external;

  function chunkCommit(EntityId caller, Vec3 chunkCoord) external;

  function respawnResource(DrandData calldata drand, ObjectType resourceType) external;

  function respawnResource(uint256 blockNumber, ObjectType resourceType) external;

  function growSeed(EntityId caller, Vec3 coord) external;
}
