// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { IActivateSystem } from "./IActivateSystem.sol";
import { IBatchSystem } from "./IBatchSystem.sol";
import { IBedSystem } from "./IBedSystem.sol";
import { IBucketSystem } from "./IBucketSystem.sol";
import { IBuildSystem } from "./IBuildSystem.sol";
import { ICraftSystem } from "./ICraftSystem.sol";
import { IDrandEvmnetSystem } from "./IDrandEvmnetSystem.sol";
import { IFarmingSystem } from "./IFarmingSystem.sol";
import { IFoodSystem } from "./IFoodSystem.sol";
import { IForceFieldSystem } from "./IForceFieldSystem.sol";
import { IGuardianSystem } from "./IGuardianSystem.sol";
import { IHitMachineSystem } from "./IHitMachineSystem.sol";
import { IHitPlayerSystem } from "./IHitPlayerSystem.sol";
import { IInventorySystem } from "./IInventorySystem.sol";
import { IMachineSystem } from "./IMachineSystem.sol";
import { IMineSystem } from "./IMineSystem.sol";
import { IMoveSystem } from "./IMoveSystem.sol";
import { INameSystem } from "./INameSystem.sol";
import { INatureSystem } from "./INatureSystem.sol";
import { IProgramSystem } from "./IProgramSystem.sol";
import { ISpawnSystem } from "./ISpawnSystem.sol";
import { ITerrainSystem } from "./ITerrainSystem.sol";
import { ITransferSystem } from "./ITransferSystem.sol";
import { IDebugSystem } from "./IDebugSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IActivateSystem,
  IBatchSystem,
  IBedSystem,
  IBucketSystem,
  IBuildSystem,
  ICraftSystem,
  IDrandEvmnetSystem,
  IFarmingSystem,
  IFoodSystem,
  IForceFieldSystem,
  IGuardianSystem,
  IHitMachineSystem,
  IHitPlayerSystem,
  IInventorySystem,
  IMachineSystem,
  IMineSystem,
  IMoveSystem,
  INameSystem,
  INatureSystem,
  IProgramSystem,
  ISpawnSystem,
  ITerrainSystem,
  ITransferSystem,
  IDebugSystem
{}
