// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "@dust/world/src/EntityId.sol";

/**
 * @title IWhitelistSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IWhitelistSystem {
  function dfprograms_1__setAllowed(EntityId target, EntityId caller, bool allowed) external;

  function dfprograms_1__setOwner(EntityId target, EntityId newOwner) external;
}
