// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ObjectTypeId } from "./ObjectTypeId.sol";
import { ObjectTypes } from "./ObjectTypes.sol";

function isFood(ObjectTypeId objectTypeId) pure returns (bool) {
  if (objectTypeId == ObjectTypes.WheatSlop) {
    return true;
  }

  return false;
}

function isCropSeed(ObjectTypeId objectTypeId) pure returns (bool) {
  if (objectTypeId == ObjectTypes.WheatSeed) {
    return true;
  }

  if (objectTypeId == ObjectTypes.MelonSeed) {
    return true;
  }

  if (objectTypeId == ObjectTypes.PumpkinSeed) {
    return true;
  }

  return false;
}

function isTreeSeed(ObjectTypeId objectTypeId) pure returns (bool) {
  if (objectTypeId == ObjectTypes.OakSapling) {
    return true;
  }

  if (objectTypeId == ObjectTypes.BirchSapling) {
    return true;
  }

  if (objectTypeId == ObjectTypes.JungleSapling) {
    return true;
  }

  if (objectTypeId == ObjectTypes.SakuraSapling) {
    return true;
  }

  if (objectTypeId == ObjectTypes.AcaciaSapling) {
    return true;
  }

  if (objectTypeId == ObjectTypes.SpruceSapling) {
    return true;
  }

  if (objectTypeId == ObjectTypes.DarkOakSapling) {
    return true;
  }

  if (objectTypeId == ObjectTypes.MangroveSapling) {
    return true;
  }

  return false;
}
