// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ObjectType } from "./ObjectType.sol";
import { ObjectTypes } from "./ObjectType.sol";

function isFood(ObjectType objectType) pure returns (bool) {
  if (objectType == ObjectTypes.WheatSlop) {
    return true;
  }

  return false;
}

function isCropSeed(ObjectType objectType) pure returns (bool) {
  if (objectType == ObjectTypes.WheatSeed) {
    return true;
  }

  return false;
}

function isTreeSeed(ObjectType objectType) pure returns (bool) {
  if (objectType == ObjectTypes.OakSeed) {
    return true;
  }

  if (objectType == ObjectTypes.SpruceSeed) {
    return true;
  }

  return false;
}
