// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ObjectType } from "./ObjectType.sol";
import { ObjectTypes } from "./ObjectType.sol";

function timeToGrow(ObjectType objectType) pure returns (uint128) {
  if (objectType == ObjectTypes.WheatSeed) {
    return 900 seconds;
  }

  if (objectType == ObjectTypes.OakSeed) {
    return 345600 seconds;
  }

  if (objectType == ObjectTypes.SpruceSeed) {
    return 345600 seconds;
  }

  return 0;
}
