// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ObjectTypeId } from "./ObjectTypeId.sol";
import { ObjectTypes } from "./ObjectTypes.sol";

function timeToGrow(ObjectTypeId objectTypeId) pure returns (uint128) {
  if (objectTypeId == ObjectTypes.WheatSeed) {
    return 900 seconds;
  }

  if (objectTypeId == ObjectTypes.MelonSeed) {
    return 3600 seconds;
  }

  if (objectTypeId == ObjectTypes.PumpkinSeed) {
    return 3600 seconds;
  }

  if (objectTypeId == ObjectTypes.OakSapling) {
    return 345600 seconds;
  }

  if (objectTypeId == ObjectTypes.BirchSapling) {
    return 345600 seconds;
  }

  if (objectTypeId == ObjectTypes.JungleSapling) {
    return 345600 seconds;
  }

  if (objectTypeId == ObjectTypes.SakuraSapling) {
    return 345600 seconds;
  }

  if (objectTypeId == ObjectTypes.AcaciaSapling) {
    return 345600 seconds;
  }

  if (objectTypeId == ObjectTypes.SpruceSapling) {
    return 345600 seconds;
  }

  if (objectTypeId == ObjectTypes.DarkOakSapling) {
    return 345600 seconds;
  }

  if (objectTypeId == ObjectTypes.MangroveSapling) {
    return 345600 seconds;
  }

  return 0;
}
