// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum NotificationType {
  None,
  Build,
  Mine,
  Move,
  Craft,
  CraftFuel,
  Drop,
  Pickup,
  Transfer,
  Spawn,
  Sleep,
  Wakeup,
  FuelMachine,
  HitMachine,
  HitPlayer,
  AttachProgram,
  DetachProgram,
  AddFragment,
  RemoveFragment,
  Death
}

enum RateLimitType {
  Movement,
  Combat,
  Work
}

enum ActivityType {
  MinePickMass,
  MineAxeMass,
  MineCropMass,
  HitPlayerDamage,
  HitMachineDamage,
  MoveWalkSteps,
  MoveSwimSteps,
  MoveFallEnergy,
  BuildEnergy,
  BuildMass
}

enum Direction {
  PositiveX,
  NegativeX,
  PositiveY,
  NegativeY,
  PositiveZ,
  NegativeZ,
  PositiveXPositiveY,
  PositiveXNegativeY,
  NegativeXPositiveY,
  NegativeXNegativeY,
  PositiveXPositiveZ,
  PositiveXNegativeZ,
  NegativeXPositiveZ,
  NegativeXNegativeZ,
  PositiveYPositiveZ,
  PositiveYNegativeZ,
  NegativeYPositiveZ,
  NegativeYNegativeZ,
  PositiveXPositiveYPositiveZ,
  PositiveXPositiveYNegativeZ,
  PositiveXNegativeYPositiveZ,
  PositiveXNegativeYNegativeZ,
  NegativeXPositiveYPositiveZ,
  NegativeXPositiveYNegativeZ,
  NegativeXNegativeYPositiveZ,
  NegativeXNegativeYNegativeZ
}
