// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ObjectPhysics, ObjectPhysicsData } from "./tables/ObjectPhysics.sol";
import { Recipes, RecipesData } from "./tables/Recipes.sol";
import { InitialEnergyPool } from "./tables/InitialEnergyPool.sol";
import { EntityObjectType } from "./tables/EntityObjectType.sol";
import { EntityFluidLevel } from "./tables/EntityFluidLevel.sol";
import { EntityPosition, EntityPositionData } from "./tables/EntityPosition.sol";
import { EntityOrientation } from "./tables/EntityOrientation.sol";
import { Mass } from "./tables/Mass.sol";
import { Energy, EnergyData } from "./tables/Energy.sol";
import { LocalEnergyPool } from "./tables/LocalEnergyPool.sol";
import { ExploredChunk } from "./tables/ExploredChunk.sol";
import { SurfaceChunkByIndex, SurfaceChunkByIndexData } from "./tables/SurfaceChunkByIndex.sol";
import { SurfaceChunkCount } from "./tables/SurfaceChunkCount.sol";
import { RegionMerkleRoot } from "./tables/RegionMerkleRoot.sol";
import { InventorySlot, InventorySlotData } from "./tables/InventorySlot.sol";
import { InventoryBitmap } from "./tables/InventoryBitmap.sol";
import { ReverseMovablePosition } from "./tables/ReverseMovablePosition.sol";
import { MoveCount } from "./tables/MoveCount.sol";
import { Death, DeathData } from "./tables/Death.sol";
import { BedPlayer, BedPlayerData } from "./tables/BedPlayer.sol";
import { PlayerBed } from "./tables/PlayerBed.sol";
import { EntityProgram } from "./tables/EntityProgram.sol";
import { Fragment, FragmentData } from "./tables/Fragment.sol";
import { Machine, MachineData } from "./tables/Machine.sol";
import { ChunkCommitment } from "./tables/ChunkCommitment.sol";
import { ResourcePosition, ResourcePositionData } from "./tables/ResourcePosition.sol";
import { ResourceCount } from "./tables/ResourceCount.sol";
import { BurnedResourceCount } from "./tables/BurnedResourceCount.sol";
import { DisabledExtraDrops } from "./tables/DisabledExtraDrops.sol";
import { SeedGrowth } from "./tables/SeedGrowth.sol";
import { Notification, NotificationData } from "./tables/Notification.sol";
import { WorldStatus } from "./tables/WorldStatus.sol";
import { Moderators } from "./tables/Moderators.sol";
import { UniqueEntity } from "./tables/UniqueEntity.sol";
import { BaseEntity } from "./tables/BaseEntity.sol";
