// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ObjectPhysics, ObjectPhysicsData } from "./tables/ObjectPhysics.sol";
import { Recipes, RecipesData } from "./tables/Recipes.sol";
import { InitialEnergyPool } from "./tables/InitialEnergyPool.sol";
import { EntityObjectType } from "./tables/EntityObjectType.sol";
import { Position, PositionData } from "./tables/Position.sol";
import { ReversePosition } from "./tables/ReversePosition.sol";
import { Orientation } from "./tables/Orientation.sol";
import { Mass } from "./tables/Mass.sol";
import { Energy, EnergyData } from "./tables/Energy.sol";
import { LocalEnergyPool } from "./tables/LocalEnergyPool.sol";
import { ExploredChunk } from "./tables/ExploredChunk.sol";
import { SurfaceChunkByIndex, SurfaceChunkByIndexData } from "./tables/SurfaceChunkByIndex.sol";
import { SurfaceChunkCount } from "./tables/SurfaceChunkCount.sol";
import { RegionMerkleRoot } from "./tables/RegionMerkleRoot.sol";
import { Inventory, InventoryData } from "./tables/Inventory.sol";
import { InventorySlot, InventorySlotData } from "./tables/InventorySlot.sol";
import { InventoryTypeSlots } from "./tables/InventoryTypeSlots.sol";
import { MovablePosition, MovablePositionData } from "./tables/MovablePosition.sol";
import { ReverseMovablePosition } from "./tables/ReverseMovablePosition.sol";
import { Player } from "./tables/Player.sol";
import { ReversePlayer } from "./tables/ReversePlayer.sol";
import { BedPlayer, BedPlayerData } from "./tables/BedPlayer.sol";
import { PlayerBed } from "./tables/PlayerBed.sol";
import { EntityProgram } from "./tables/EntityProgram.sol";
import { Fragment, FragmentData } from "./tables/Fragment.sol";
import { FragmentPosition, FragmentPositionData } from "./tables/FragmentPosition.sol";
import { ReverseFragmentPosition } from "./tables/ReverseFragmentPosition.sol";
import { Machine, MachineData } from "./tables/Machine.sol";
import { ChunkCommitment } from "./tables/ChunkCommitment.sol";
import { ResourcePosition, ResourcePositionData } from "./tables/ResourcePosition.sol";
import { ResourceCount } from "./tables/ResourceCount.sol";
import { BurnedResourceCount } from "./tables/BurnedResourceCount.sol";
import { DisabledExtraDrops } from "./tables/DisabledExtraDrops.sol";
import { SeedGrowth } from "./tables/SeedGrowth.sol";
import { Notification, NotificationData } from "./tables/Notification.sol";
import { WorldStatus } from "./tables/WorldStatus.sol";
import { UniqueEntity } from "./tables/UniqueEntity.sol";
import { BaseEntity } from "./tables/BaseEntity.sol";
