// Script to add new objects and recipes from new-recipes.md

// New object names to add
export const newObjectNames = [
  // New base materials
  "Cotton",
  "Glass", 
  "Brick",
  "BrickBlock",
  "MudBricks",
  "Paper",
  "Book",
  "Stick",
  "CottonSeed",
  "Stonecutter",
  
  // Dyes
  "RedDye",
  "YellowDye",
  "BlueDye",
  "GreenDye",
  "WhiteDye",
  "BlackDye",
  "BrownDye",
  "OrangeDye",
  "PinkDye",
  "LimeDye",
  "CyanDye",
  "GrayDye",
  "PurpleDye",
  
  // Colored Cotton
  "RedCotton",
  "YellowCotton",
  "BlueCotton",
  "GreenCotton",
  "WhiteCotton",
  "BlackCotton",
  "BrownCotton",
  "OrangeCotton",
  "PinkCotton",
  "LimeCotton",
  "CyanCotton",
  "GrayCotton",
  "PurpleCotton",
  
  // Colored Terracotta (some already exist)
  "GreenTerracotta",
  "PinkTerracotta",
  "LimeTerracotta",
  "GrayTerracotta",
  
  // Concrete Powder
  "RedConcretePowder",
  "YellowConcretePowder",
  "BlueConcretePowder",
  "GreenConcretePowder",
  "WhiteConcretePowder",
  "BlackConcretePowder",
  "BrownConcretePowder",
  "OrangeConcretePowder",
  "PinkConcretePowder",
  "LimeConcretePowder",
  "CyanConcretePowder",
  "GrayConcretePowder",
  "PurpleConcretePowder",
  
  // Concrete
  "RedConcrete",
  "YellowConcrete",
  "BlueConcrete",
  "GreenConcrete",
  "WhiteConcrete",
  "BlackConcrete",
  "BrownConcrete",
  "OrangeConcrete",
  "PinkConcrete",
  "LimeConcrete",
  "CyanConcrete",
  "GrayConcrete",
  "PurpleConcrete",
  
  // Stone variants
  "StoneBricks",
  "TuffBricks",
  "DeepslateBricks",
  "PolishedAndesite",
  "PolishedGranite",
  "PolishedDiorite",
  "PolishedTuff",
  "PolishedBasalt",
  "PolishedBlackstone",
  "ChiseledStoneBricks",
  "ChiseledTuffBricks",
  "ChiseledDeepslate",
  "ChiseledPolishedBlackstone",
  "ChiseledSandstone",
  "ChiseledRedSandstone",
  "CrackedStoneBricks",
  "CrackedTuffBricks",
  "CrackedDeepslateBricks",
  "SmoothSandstone",
  "SmoothRedSandstone",
  "SmoothStone",
  
  // Functional blocks
  "GlassPane",
  "Barrel",
  "Bookshelf",
  "Carpet",
  "RedCarpet",
  "YellowCarpet",
  "BlueCarpet",
  "GreenCarpet",
  "WhiteCarpet",
  "BlackCarpet",
  "BrownCarpet",
  "OrangeCarpet",
  "PinkCarpet",
  "LimeCarpet",
  "CyanCarpet",
  "GrayCarpet",
  "PurpleCarpet",
  "FlowerPot",
  "Lodestone",
  "Lantern",
  "Ladder",
  "IronBars",
  
  // Doors
  "OakDoor",
  "BirchDoor",
  "JungleDoor",
  "SakuraDoor",
  "AcaciaDoor",
  "SpruceDoor",
  "DarkOakDoor",
  "MangroveDoor",
  "IronDoor",
  
  // Trapdoors
  "OakTrapdoor",
  "BirchTrapdoor",
  "JungleTrapdoor",
  "SakuraTrapdoor",
  "AcaciaTrapdoor",
  "SpruceTrapdoor",
  "DarkOakTrapdoor",
  "MangroveTrapdoor",
  "IronTrapdoor",
  
  // Fences
  "OakFence",
  "BirchFence",
  "JungleFence",
  "SakuraFence",
  "AcaciaFence",
  "SpruceFence",
  "DarkOakFence",
  "MangroveFence",
  
  // Fence Gates
  "OakFenceGate",
  "BirchFenceGate",
  "JungleFenceGate",
  "SakuraFenceGate",
  "AcaciaFenceGate",
  "SpruceFenceGate",
  "DarkOakFenceGate",
  "MangroveFenceGate",
  
  // Stairs
  "StoneStairs",
  "CobblestoneStairs",
  "MossyCobblestoneStairs",
  "StoneBricksStairs",
  "SmoothStoneStairs",
  "AndesiteStairs",
  "GraniteStairs",
  "DioriteStairs",
  "TuffStairs",
  "BasaltStairs",
  "BlackstoneStairs",
  "PolishedAndesiteStairs",
  "PolishedGraniteStairs",
  "PolishedDioriteStairs",
  "PolishedTuffStairs",
  "PolishedBasaltStairs",
  "PolishedBlackstoneStairs",
  "DeepslateStairs",
  "CobbledDeepslateStairs",
  "DeepslateBricksStairs",
  "SandstoneStairs",
  "RedSandstoneStairs",
  "SmoothSandstoneStairs",
  "SmoothRedSandstoneStairs",
  "BrickBlockStairs",
  "MudBricksStairs",
  "TuffBricksStairs",
  "RedConcreteStairs",
  "YellowConcreteStairs",
  "BlueConcreteStairs",
  "GreenConcreteStairs",
  "WhiteConcreteStairs",
  "BlackConcreteStairs",
  "BrownConcreteStairs",
  "OrangeConcreteStairs",
  "PinkConcreteStairs",
  "LimeConcreteStairs",
  "CyanConcreteStairs",
  "GrayConcreteStairs",
  "PurpleConcreteStairs",
  "OakPlanksStairs",
  "BirchPlanksStairs",
  "JunglePlanksStairs",
  "SakuraPlanksStairs",
  "SprucePlanksStairs",
  "AcaciaPlanksStairs",
  "DarkOakPlanksStairs",
  "MangrovePlanksStairs",
  
  // Slabs
  "StoneSlab",
  "CobblestoneSlab",
  "MossyCobblestoneSlab",
  "StoneBricksSlab",
  "SmoothStoneSlab",
  "AndesiteSlab",
  "GraniteSlab",
  "DioriteSlab",
  "TuffSlab",
  "BasaltSlab",
  "BlackstoneSlab",
  "PolishedAndesiteSlab",
  "PolishedGraniteSlab",
  "PolishedDioriteSlab",
  "PolishedTuffSlab",
  "PolishedBasaltSlab",
  "PolishedBlackstoneSlab",
  "DeepslateSlab",
  "CobbledDeepslateSlab",
  "DeepslateBricksSlab",
  "SandstoneSlab",
  "RedSandstoneSlab",
  "SmoothSandstoneSlab",
  "SmoothRedSandstoneSlab",
  "BrickBlockSlab",
  "MudBricksSlab",
  "TuffBricksSlab",
  "RedConcreteSlab",
  "YellowConcreteSlab",
  "BlueConcreteSlab",
  "GreenConcreteSlab",
  "WhiteConcreteSlab",
  "BlackConcreteSlab",
  "BrownConcreteSlab",
  "OrangeConcreteSlab",
  "PinkConcreteSlab",
  "LimeConcreteSlab",
  "CyanConcreteSlab",
  "GrayConcreteSlab",
  "PurpleConcreteSlab",
  "OakPlanksSlab",
  "BirchPlanksSlab",
  "JunglePlanksSlab",
  "SakuraPlanksSlab",
  "SprucePlanksSlab",
  "AcaciaPlanksSlab",
  "DarkOakPlanksSlab",
  "MangrovePlanksSlab",
  
  // Walls
  "StoneWall",
  "CobblestoneWall",
  "MossyCobblestoneWall",
  "StoneBricksWall",
  "AndesiteWall",
  "GraniteWall",
  "DioriteWall",
  "TuffWall",
  "BasaltWall",
  "BlackstoneWall",
  "PolishedAndesiteWall",
  "PolishedGraniteWall",
  "PolishedDioriteWall",
  "PolishedTuffWall",
  "PolishedBasaltWall",
  "PolishedBlackstoneWall",
  "DeepslateWall",
  "CobbledDeepslateWall",
  "DeepslateBricksWall",
  "SandstoneWall",
  "RedSandstoneWall",
  "SmoothSandstoneWall",
  "SmoothRedSandstoneWall",
  "BrickBlockWall",
  "MudBricksWall",
  "TuffBricksWall",
  "RedConcreteWall",
  "YellowConcreteWall",
  "BlueConcreteWall",
  "GreenConcreteWall",
  "WhiteConcreteWall",
  "BlackConcreteWall",
  "BrownConcreteWall",
  "OrangeConcreteWall",
  "PinkConcreteWall",
  "LimeConcreteWall",
  "CyanConcreteWall",
  "GrayConcreteWall",
  "PurpleConcreteWall",
  
  // Potted plants
  "PottedOakSapling",
  "PottedBirchSapling",
  "PottedJungleSapling",
  "PottedSakuraSapling",
  "PottedAcaciaSapling",
  "PottedSpruceSapling",
  "PottedDarkOakSapling",
  "PottedMangroveSapling",
];

// Object definitions with mass
export const newObjectDefs = `
  // New base materials
  { name: "Cotton", mass: 300000000000000n },
  { name: "Glass", mass: 4000000000000000n },
  { name: "Brick", mass: 2400000000000000n },
  { name: "BrickBlock", mass: 9600000000000000n },
  { name: "MudBricks", mass: 20000000000000000n },
  { name: "Paper", mass: 200000000000000n },
  { name: "Book", mass: 900000000000000n },
  { name: "Stick", mass: 2250000000000000n },
  { name: "CottonSeed" },
  { name: "Stonecutter", mass: 1035000000000000000n },
  
  // Dyes (0 mass as specified)
  { name: "RedDye", mass: 0n },
  { name: "YellowDye", mass: 0n },
  { name: "BlueDye", mass: 0n },
  { name: "GreenDye", mass: 0n },
  { name: "WhiteDye", mass: 0n },
  { name: "BlackDye", mass: 0n },
  { name: "BrownDye", mass: 0n },
  { name: "OrangeDye", mass: 0n },
  { name: "PinkDye", mass: 0n },
  { name: "LimeDye", mass: 0n },
  { name: "CyanDye", mass: 0n },
  { name: "GrayDye", mass: 0n },
  { name: "PurpleDye", mass: 0n },
`;

// New recipes
export const newRecipes = [
  // Material recipes
  { inputs: [["Mud", 4]], outputs: [["PackedMud", 4]] },
  { station: "Furnace", inputs: [["PackedMud", 4], ["CoalOre", 1]], outputs: [["MudBricks", 4]] },
  { inputs: [["IronBar", 1], ["Stone", 3]], outputs: [["Stonecutter", 1]] },
  { inputs: [["BambooBush", 3]], outputs: [["Paper", 3]] },
  { inputs: [["Paper", 3], ["Cotton", 1]], outputs: [["Book", 1]] },
  { station: "Furnace", inputs: [["Sand", 1], ["CoalOre", 1]], outputs: [["Glass", 1]] },
  { station: "Furnace", inputs: [["Clay", 1], ["CoalOre", 1]], outputs: [["Brick", 1]] },
  { station: "Furnace", inputs: [["Clay", 1]], outputs: [["Terracotta", 1]] },
  { inputs: [["Brick", 4]], outputs: [["BrickBlock", 1]] },
  { station: "Furnace", inputs: [["Cobblestone", 1], ["CoalOre", 1]], outputs: [["Stone", 1]] },
  { station: "Furnace", inputs: [["CobbledDeepslate", 1], ["CoalOre", 1]], outputs: [["Deepslate", 1]] },
  { inputs: [["AnyPlank", 2]], outputs: [["Stick", 4]] },
  
  // Dye recipes
  { inputs: [["RoseFlower", 1]], outputs: [["RedDye", 2]] },
  { inputs: [["RedMushroom", 1]], outputs: [["RedDye", 2]] },
  { inputs: [["StrawberryBush", 1]], outputs: [["RedDye", 2]] },
  { inputs: [["SunFlower", 1]], outputs: [["YellowDye", 2]] },
  { inputs: [["DandelionFlower", 1]], outputs: [["YellowDye", 2]] },
  { inputs: [["Ultraviolet", 1]], outputs: [["BlueDye", 2]] },
  { inputs: [["AnyLeaf", 1]], outputs: [["GreenDye", 1]] },
  { inputs: [["Moss", 1]], outputs: [["GreenDye", 1]] },
  { inputs: [["Calcite", 1]], outputs: [["WhiteDye", 3]] },
  { inputs: [["Bone", 1]], outputs: [["WhiteDye", 3]] },
  { inputs: [["CoalOre", 1]], outputs: [["BlackDye", 2]] },
  { inputs: [["Mud", 1]], outputs: [["BrownDye", 2]] },
  { inputs: [["BrownMushroomBlock", 1]], outputs: [["BrownDye", 2]] },
  { inputs: [["RedDye", 1], ["YellowDye", 1]], outputs: [["OrangeDye", 2]] },
  { inputs: [["RedDye", 1], ["WhiteDye", 1]], outputs: [["PinkDye", 2]] },
  { inputs: [["GreenDye", 1], ["WhiteDye", 1]], outputs: [["LimeDye", 2]] },
  { inputs: [["BlueDye", 1], ["GreenDye", 1]], outputs: [["CyanDye", 2]] },
  { inputs: [["BlackDye", 1], ["WhiteDye", 1]], outputs: [["GrayDye", 2]] },
  { inputs: [["RedDye", 1], ["BlueDye", 1]], outputs: [["PurpleDye", 2]] },
  
  // Stone variant recipes
  { inputs: [["Stone", 4]], outputs: [["StoneBricks", 4]] },
  { inputs: [["Tuff", 4]], outputs: [["TuffBricks", 4]] },
  { inputs: [["CobbledDeepslate", 4]], outputs: [["DeepslateBricks", 4]] },
  { inputs: [["Sand", 4]], outputs: [["Sandstone", 4]] },
  { inputs: [["RedSand", 4]], outputs: [["RedSandstone", 4]] },
  { station: "Stonecutter", inputs: [["Andesite", 4]], outputs: [["PolishedAndesite", 4]] },
  { station: "Stonecutter", inputs: [["Granite", 4]], outputs: [["PolishedGranite", 4]] },
  { station: "Stonecutter", inputs: [["Diorite", 4]], outputs: [["PolishedDiorite", 4]] },
  { station: "Stonecutter", inputs: [["Tuff", 4]], outputs: [["PolishedTuff", 4]] },
  { station: "Stonecutter", inputs: [["Basalt", 4]], outputs: [["PolishedBasalt", 4]] },
  { station: "Stonecutter", inputs: [["Blackstone", 4]], outputs: [["PolishedBlackstone", 4]] },
  { station: "Stonecutter", inputs: [["StoneBricks", 2]], outputs: [["ChiseledStoneBricks", 1]] },
  { station: "Stonecutter", inputs: [["TuffBricks", 2]], outputs: [["ChiseledTuffBricks", 1]] },
  { station: "Stonecutter", inputs: [["DeepslateBricks", 2]], outputs: [["ChiseledDeepslate", 1]] },
  { station: "Stonecutter", inputs: [["PolishedBlackstone", 2]], outputs: [["ChiseledPolishedBlackstone", 1]] },
  { station: "Stonecutter", inputs: [["Sandstone", 2]], outputs: [["ChiseledSandstone", 1]] },
  { station: "Stonecutter", inputs: [["RedSandstone", 2]], outputs: [["ChiseledRedSandstone", 1]] },
  { station: "Workbench", inputs: [["StoneBricks", 4]], outputs: [["CrackedStoneBricks", 4]] },
  { station: "Workbench", inputs: [["TuffBricks", 4]], outputs: [["CrackedTuffBricks", 4]] },
  { station: "Workbench", inputs: [["DeepslateBricks", 4]], outputs: [["CrackedDeepslateBricks", 4]] },
  { station: "Stonecutter", inputs: [["Sandstone", 4]], outputs: [["SmoothSandstone", 4]] },
  { station: "Stonecutter", inputs: [["RedSandstone", 4]], outputs: [["SmoothRedSandstone", 4]] },
  { station: "Stonecutter", inputs: [["Stone", 4]], outputs: [["SmoothStone", 4]] },
  
  // Functional blocks
  { station: "Workbench", inputs: [["Glass", 6]], outputs: [["GlassPane", 16]] },
  { inputs: [["AnyPlank", 6], ["OakSlab", 2]], outputs: [["Barrel", 1]] },
  { inputs: [["AnyPlank", 6], ["Book", 3]], outputs: [["Bookshelf", 1]] },
  { inputs: [["Cotton", 2]], outputs: [["Carpet", 3]] },
  { inputs: [["Brick", 3]], outputs: [["FlowerPot", 1]] },
  { inputs: [["Stone", 8], ["NeptuniumBar", 1]], outputs: [["Lodestone", 1]] },
  { inputs: [["IronBar", 1], ["Torch", 1]], outputs: [["Lantern", 1]] },
  { inputs: [["Stick", 7]], outputs: [["Ladder", 3]] },
  { inputs: [["IronBar", 6]], outputs: [["IronBars", 16]] },
  
  // Special bed recipe update
  { inputs: [["Cotton", 3], ["AnyPlank", 3]], outputs: [["Bed", 1]] },
];

console.log("New objects to add:", newObjectNames.length);
console.log("New recipes to add:", newRecipes.length);