import type { categories } from "./objects";

function validateUniqueIds<T extends readonly BiomeDefinition[]>(
  objects: T,
): T {
  const ids = new Set<number>();
  for (const obj of objects) {
    if (ids.has(obj.id)) {
      throw new Error(`Duplicate ID found: ${obj.id} for object ${obj.name}`);
    }
    ids.add(obj.id);
  }
  return objects;
}

export const biomeNames = [
  "badlands",
  "bamboo_jungle",
  "basalt_deltas",
  "beach",
  "birch_forest",
  "cherry_grove",
  "cold_ocean",
  "crimson_forest",
  "dark_forest",
  "deep_cold_ocean",
  "deep_dark",
  "deep_frozen_ocean",
  "deep_lukewarm_ocean",
  "deep_ocean",
  "desert",
  "dripstone_caves",
  "end_barrens",
  "end_highlands",
  "end_midlands",
  "eroded_badlands",
  "flower_forest",
  "forest",
  "frozen_ocean",
  "frozen_peaks",
  "frozen_river",
  "grove",
  "ice_spikes",
  "jagged_peaks",
  "jungle",
  "lukewarm_ocean",
  "lush_caves",
  "mangrove_swamp",
  "meadow",
  "mushroom_fields",
  "nether_wastes",
  "ocean",
  "old_growth_birch_forest",
  "old_growth_pine_taiga",
  "old_growth_spruce_taiga",
  "plains",
  "river",
  "savanna",
  "savanna_plateau",
  "small_end_islands",
  "snowy_beach",
  "snowy_plains",
  "snowy_slopes",
  "snowy_taiga",
  "soul_sand_valley",
  "sparse_jungle",
  "stony_peaks",
  "stony_shore",
  "sunflower_plains",
  "swamp",
  "taiga",
  "the_end",
  "the_void",
  "warm_ocean",
  "warped_forest",
  "windswept_forest",
  "windswept_gravelly_hills",
  "windswept_hills",
  "windswept_savanna",
  "wooded_badlands",
  "desert_canyon",
  "andesite_caves",
  "crystal_caves",
  "deep_caves",
  "desert_caves",
  "diorite_caves",
  "frostfire_caves",
  "fungal_caves",
  "granite_caves",
  "ice_caves",
  "infested_caves",
  "mantle_caves",
  "thermal_caves",
  "tuff_caves",
  "underground_jungle",
  "alpha_islands_winter",
  "alpha_islands",
  "alpine_grove",
  "alpine_highlands",
  "amethyst_canyon",
  "amethyst_rainforest",
  "ancient_sands",
  "arid_highlands",
  "ashen_savanna",
  "basalt_cliffs",
  "birch_taiga",
  "blooming_plateau",
  "blooming_valley",
  "brushland",
  "bryce_canyon",
  "caldera",
  "cloud_forest",
  "cold_shrubland",
  "desert_oasis",
  "desert_spires",
  "emerald_peaks",
  "forested_highlands",
  "fractured_savanna",
  "frozen_cliffs",
  "glacial_chasm",
  "granite_cliffs",
  "gravel_beach",
  "gravel_desert",
  "haze_mountain",
  "highlands",
  "hot_shrubland",
  "ice_marsh",
  "jungle_mountains",
  "lavender_forest",
  "lavender_valley",
  "lush_desert",
  "lush_valley",
  "mirage_isles",
  "moonlight_grove",
  "moonlight_valley",
  "mountain_steppe",
  "orchid_swamp",
  "painted_mountains",
  "red_oasis",
  "rocky_jungle",
  "rocky_mountains",
  "rocky_shrubland",
  "sakura_grove",
  "sakura_valley",
  "sandstone_valley",
  "savanna_badlands",
  "savanna_slopes",
  "scarlet_mountains",
  "shield_clearing",
  "shield",
  "shrubland",
  "siberian_grove",
  "siberian_taiga",
  "skylands_autumn",
  "skylands_spring",
  "skylands_summer",
  "skylands_winter",
  "skylands",
  "snowy_badlands",
  "snowy_cherry_grove",
  "snowy_maple_forest",
  "snowy_shield",
  "steppe",
  "stony_spires",
  "temperate_highlands",
  "tropical_jungle",
  "valley_clearing",
  "volcanic_crater",
  "volcanic_peaks",
  "warm_river",
  "warped_mesa",
  "white_cliffs",
  "white_mesa",
  "windswept_spires",
  "wintry_forest",
  "wintry_lowlands",
  "yellowstone",
  "yosemite_cliffs",
  "yosemite_lowlands",
] as const;

export type BiomeName = (typeof biomeNames)[number];

type OreArray = typeof categories.Ore.objects;
type ArrayToTuple<T extends readonly unknown[]> = {
  readonly [K in keyof T]: [T[K], number];
};
type OreMultipliers = ArrayToTuple<OreArray>;

export interface BiomeDefinition {
  name: BiomeName;
  id: number;
  oreMultipliers: OreMultipliers;
}

export const biomes: readonly BiomeDefinition[] = validateUniqueIds([
  {
    name: "badlands",
    id: 0,
    oreMultipliers: [
      ["CoalOre", 158630],
      ["CopperOre", 40481],
      ["IronOre", 38193],
      ["GoldOre", 64501],
      ["DiamondOre", 0],
      ["NeptuniumOre", 10],
    ],
  },
  {
    name: "bamboo_jungle",
    id: 1,
    oreMultipliers: [
      ["CoalOre", 57471],
      ["CopperOre", 31767],
      ["IronOre", 4289],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "basalt_deltas",
    id: 2,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "beach",
    id: 3,
    oreMultipliers: [
      ["CoalOre", 27683],
      ["CopperOre", 21550],
      ["IronOre", 10145],
      ["GoldOre", 399],
      ["DiamondOre", 47],
      ["NeptuniumOre", 1],
    ],
  },
  {
    name: "birch_forest",
    id: 4,
    oreMultipliers: [
      ["CoalOre", 10803],
      ["CopperOre", 7176],
      ["IronOre", 1527],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "cherry_grove",
    id: 5,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "cold_ocean",
    id: 6,
    oreMultipliers: [
      ["CoalOre", 14560],
      ["CopperOre", 16742],
      ["IronOre", 15917],
      ["GoldOre", 3239],
      ["DiamondOre", 1175],
      ["NeptuniumOre", 1],
    ],
  },
  {
    name: "crimson_forest",
    id: 7,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "dark_forest",
    id: 8,
    oreMultipliers: [
      ["CoalOre", 53449],
      ["CopperOre", 28113],
      ["IronOre", 5193],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "deep_cold_ocean",
    id: 9,
    oreMultipliers: [
      ["CoalOre", 1899],
      ["CopperOre", 14055],
      ["IronOre", 56715],
      ["GoldOre", 39434],
      ["DiamondOre", 23289],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "deep_dark",
    id: 10,
    oreMultipliers: [
      ["CoalOre", 283659],
      ["CopperOre", 326206],
      ["IronOre", 372641],
      ["GoldOre", 128409],
      ["DiamondOre", 75506],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "deep_frozen_ocean",
    id: 11,
    oreMultipliers: [
      ["CoalOre", 124],
      ["CopperOre", 1076],
      ["IronOre", 3544],
      ["GoldOre", 3066],
      ["DiamondOre", 3200],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "deep_lukewarm_ocean",
    id: 12,
    oreMultipliers: [
      ["CoalOre", 81],
      ["CopperOre", 653],
      ["IronOre", 1702],
      ["GoldOre", 1671],
      ["DiamondOre", 880],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "deep_ocean",
    id: 13,
    oreMultipliers: [
      ["CoalOre", 877],
      ["CopperOre", 7499],
      ["IronOre", 22198],
      ["GoldOre", 12122],
      ["DiamondOre", 5262],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "desert",
    id: 14,
    oreMultipliers: [
      ["CoalOre", 24979],
      ["CopperOre", 11337],
      ["IronOre", 5129],
      ["GoldOre", 267],
      ["DiamondOre", 36],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "dripstone_caves",
    id: 15,
    oreMultipliers: [
      ["CoalOre", 1944385],
      ["CopperOre", 2575960],
      ["IronOre", 615503],
      ["GoldOre", 69362],
      ["DiamondOre", 39301],
      ["NeptuniumOre", 268],
    ],
  },
  {
    name: "end_barrens",
    id: 16,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "end_highlands",
    id: 17,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "end_midlands",
    id: 18,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "eroded_badlands",
    id: 19,
    oreMultipliers: [
      ["CoalOre", 145324],
      ["CopperOre", 13519],
      ["IronOre", 33882],
      ["GoldOre", 54786],
      ["DiamondOre", 16],
      ["NeptuniumOre", 3],
    ],
  },
  {
    name: "flower_forest",
    id: 20,
    oreMultipliers: [
      ["CoalOre", 8624],
      ["CopperOre", 5506],
      ["IronOre", 1095],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "forest",
    id: 21,
    oreMultipliers: [
      ["CoalOre", 83114],
      ["CopperOre", 32743],
      ["IronOre", 15175],
      ["GoldOre", 126],
      ["DiamondOre", 7],
      ["NeptuniumOre", 4],
    ],
  },
  {
    name: "frozen_ocean",
    id: 22,
    oreMultipliers: [
      ["CoalOre", 4771],
      ["CopperOre", 6153],
      ["IronOre", 7345],
      ["GoldOre", 1963],
      ["DiamondOre", 1296],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "frozen_peaks",
    id: 23,
    oreMultipliers: [
      ["CoalOre", 6038],
      ["CopperOre", 0],
      ["IronOre", 3155],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 181],
    ],
  },
  {
    name: "frozen_river",
    id: 24,
    oreMultipliers: [
      ["CoalOre", 11816],
      ["CopperOre", 11806],
      ["IronOre", 6657],
      ["GoldOre", 216],
      ["DiamondOre", 32],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "grove",
    id: 25,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "ice_spikes",
    id: 26,
    oreMultipliers: [
      ["CoalOre", 6],
      ["CopperOre", 54],
      ["IronOre", 8],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "jagged_peaks",
    id: 27,
    oreMultipliers: [
      ["CoalOre", 29774],
      ["CopperOre", 0],
      ["IronOre", 17387],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 997],
    ],
  },
  {
    name: "jungle",
    id: 28,
    oreMultipliers: [
      ["CoalOre", 171088],
      ["CopperOre", 35114],
      ["IronOre", 37347],
      ["GoldOre", 55],
      ["DiamondOre", 0],
      ["NeptuniumOre", 12],
    ],
  },
  {
    name: "lukewarm_ocean",
    id: 29,
    oreMultipliers: [
      ["CoalOre", 42689],
      ["CopperOre", 51221],
      ["IronOre", 52918],
      ["GoldOre", 10300],
      ["DiamondOre", 2874],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "lush_caves",
    id: 30,
    oreMultipliers: [
      ["CoalOre", 1433781],
      ["CopperOre", 1173465],
      ["IronOre", 1366742],
      ["GoldOre", 428359],
      ["DiamondOre", 369632],
      ["NeptuniumOre", 135],
    ],
  },
  {
    name: "mangrove_swamp",
    id: 31,
    oreMultipliers: [
      ["CoalOre", 108941],
      ["CopperOre", 17131],
      ["IronOre", 15688],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "meadow",
    id: 32,
    oreMultipliers: [
      ["CoalOre", 76],
      ["CopperOre", 54],
      ["IronOre", 5],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 1],
    ],
  },
  {
    name: "mushroom_fields",
    id: 33,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "nether_wastes",
    id: 34,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "ocean",
    id: 35,
    oreMultipliers: [
      ["CoalOre", 103206],
      ["CopperOre", 113110],
      ["IronOre", 91257],
      ["GoldOre", 9939],
      ["DiamondOre", 2272],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "old_growth_birch_forest",
    id: 36,
    oreMultipliers: [
      ["CoalOre", 9927],
      ["CopperOre", 4335],
      ["IronOre", 1846],
      ["GoldOre", 14],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "old_growth_pine_taiga",
    id: 37,
    oreMultipliers: [
      ["CoalOre", 20109],
      ["CopperOre", 8862],
      ["IronOre", 2825],
      ["GoldOre", 6],
      ["DiamondOre", 0],
      ["NeptuniumOre", 1],
    ],
  },
  {
    name: "old_growth_spruce_taiga",
    id: 38,
    oreMultipliers: [
      ["CoalOre", 82084],
      ["CopperOre", 2807],
      ["IronOre", 23332],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 6],
    ],
  },
  {
    name: "plains",
    id: 39,
    oreMultipliers: [
      ["CoalOre", 51709],
      ["CopperOre", 35117],
      ["IronOre", 8474],
      ["GoldOre", 50],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "river",
    id: 40,
    oreMultipliers: [
      ["CoalOre", 118554],
      ["CopperOre", 114143],
      ["IronOre", 55566],
      ["GoldOre", 1656],
      ["DiamondOre", 47],
      ["NeptuniumOre", 1],
    ],
  },
  {
    name: "savanna",
    id: 41,
    oreMultipliers: [
      ["CoalOre", 235597],
      ["CopperOre", 60799],
      ["IronOre", 50702],
      ["GoldOre", 629],
      ["DiamondOre", 51],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "savanna_plateau",
    id: 42,
    oreMultipliers: [
      ["CoalOre", 122850],
      ["CopperOre", 21487],
      ["IronOre", 27411],
      ["GoldOre", 192],
      ["DiamondOre", 11],
      ["NeptuniumOre", 9],
    ],
  },
  {
    name: "small_end_islands",
    id: 43,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "snowy_beach",
    id: 44,
    oreMultipliers: [
      ["CoalOre", 938],
      ["CopperOre", 872],
      ["IronOre", 538],
      ["GoldOre", 42],
      ["DiamondOre", 0],
      ["NeptuniumOre", 1],
    ],
  },
  {
    name: "snowy_plains",
    id: 45,
    oreMultipliers: [
      ["CoalOre", 207954],
      ["CopperOre", 71349],
      ["IronOre", 33988],
      ["GoldOre", 77],
      ["DiamondOre", 3],
      ["NeptuniumOre", 8],
    ],
  },
  {
    name: "snowy_slopes",
    id: 46,
    oreMultipliers: [
      ["CoalOre", 7303],
      ["CopperOre", 0],
      ["IronOre", 2929],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 201],
    ],
  },
  {
    name: "snowy_taiga",
    id: 47,
    oreMultipliers: [
      ["CoalOre", 71081],
      ["CopperOre", 39136],
      ["IronOre", 12169],
      ["GoldOre", 93],
      ["DiamondOre", 3],
      ["NeptuniumOre", 2],
    ],
  },
  {
    name: "soul_sand_valley",
    id: 48,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "sparse_jungle",
    id: 49,
    oreMultipliers: [
      ["CoalOre", 260045],
      ["CopperOre", 128533],
      ["IronOre", 27375],
      ["GoldOre", 38],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "stony_peaks",
    id: 50,
    oreMultipliers: [
      ["CoalOre", 254920],
      ["CopperOre", 0],
      ["IronOre", 187421],
      ["GoldOre", 4],
      ["DiamondOre", 0],
      ["NeptuniumOre", 9636],
    ],
  },
  {
    name: "stony_shore",
    id: 51,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "sunflower_plains",
    id: 52,
    oreMultipliers: [
      ["CoalOre", 95],
      ["CopperOre", 88],
      ["IronOre", 19],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "swamp",
    id: 53,
    oreMultipliers: [
      ["CoalOre", 18145],
      ["CopperOre", 4713],
      ["IronOre", 2704],
      ["GoldOre", 1],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "taiga",
    id: 54,
    oreMultipliers: [
      ["CoalOre", 4708],
      ["CopperOre", 1429],
      ["IronOre", 1411],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "the_end",
    id: 55,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "the_void",
    id: 56,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "warm_ocean",
    id: 57,
    oreMultipliers: [
      ["CoalOre", 4193],
      ["CopperOre", 5809],
      ["IronOre", 6773],
      ["GoldOre", 1554],
      ["DiamondOre", 379],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "warped_forest",
    id: 58,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "windswept_forest",
    id: 59,
    oreMultipliers: [
      ["CoalOre", 11644],
      ["CopperOre", 6600],
      ["IronOre", 1000],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 219],
    ],
  },
  {
    name: "windswept_gravelly_hills",
    id: 60,
    oreMultipliers: [
      ["CoalOre", 763],
      ["CopperOre", 946],
      ["IronOre", 532],
      ["GoldOre", 50],
      ["DiamondOre", 20],
      ["NeptuniumOre", 15],
    ],
  },
  {
    name: "windswept_hills",
    id: 61,
    oreMultipliers: [
      ["CoalOre", 7117],
      ["CopperOre", 5073],
      ["IronOre", 1067],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 146],
    ],
  },
  {
    name: "windswept_savanna",
    id: 62,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "wooded_badlands",
    id: 63,
    oreMultipliers: [
      ["CoalOre", 12160],
      ["CopperOre", 10851],
      ["IronOre", 4567],
      ["GoldOre", 7064],
      ["DiamondOre", 4],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "desert_canyon",
    id: 64,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "andesite_caves",
    id: 65,
    oreMultipliers: [
      ["CoalOre", 607673],
      ["CopperOre", 423945],
      ["IronOre", 383418],
      ["GoldOre", 76794],
      ["DiamondOre", 38956],
      ["NeptuniumOre", 3],
    ],
  },
  {
    name: "crystal_caves",
    id: 66,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "deep_caves",
    id: 67,
    oreMultipliers: [
      ["CoalOre", 109319],
      ["CopperOre", 141845],
      ["IronOre", 285160],
      ["GoldOre", 177931],
      ["DiamondOre", 223616],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "desert_caves",
    id: 68,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "diorite_caves",
    id: 69,
    oreMultipliers: [
      ["CoalOre", 200901],
      ["CopperOre", 150917],
      ["IronOre", 137323],
      ["GoldOre", 23369],
      ["DiamondOre", 10666],
      ["NeptuniumOre", 9],
    ],
  },
  {
    name: "frostfire_caves",
    id: 70,
    oreMultipliers: [
      ["CoalOre", 3032],
      ["CopperOre", 4257],
      ["IronOre", 15727],
      ["GoldOre", 10087],
      ["DiamondOre", 10967],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "fungal_caves",
    id: 71,
    oreMultipliers: [
      ["CoalOre", 999188],
      ["CopperOre", 136396],
      ["IronOre", 105961],
      ["GoldOre", 22242],
      ["DiamondOre", 13792],
      ["NeptuniumOre", 42],
    ],
  },
  {
    name: "granite_caves",
    id: 72,
    oreMultipliers: [
      ["CoalOre", 941030],
      ["CopperOre", 436557],
      ["IronOre", 363609],
      ["GoldOre", 59301],
      ["DiamondOre", 28370],
      ["NeptuniumOre", 122],
    ],
  },
  {
    name: "ice_caves",
    id: 73,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "infested_caves",
    id: 74,
    oreMultipliers: [
      ["CoalOre", 116609],
      ["CopperOre", 104126],
      ["IronOre", 123571],
      ["GoldOre", 38410],
      ["DiamondOre", 25798],
      ["NeptuniumOre", 1],
    ],
  },
  {
    name: "mantle_caves",
    id: 75,
    oreMultipliers: [
      ["CoalOre", 748748],
      ["CopperOre", 566093],
      ["IronOre", 778619],
      ["GoldOre", 342314],
      ["DiamondOre", 313924],
      ["NeptuniumOre", 25],
    ],
  },
  {
    name: "thermal_caves",
    id: 76,
    oreMultipliers: [
      ["CoalOre", 236770],
      ["CopperOre", 127777],
      ["IronOre", 126447],
      ["GoldOre", 34498],
      ["DiamondOre", 22813],
      ["NeptuniumOre", 59],
    ],
  },
  {
    name: "tuff_caves",
    id: 77,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 389],
      ["IronOre", 25936],
      ["GoldOre", 29314],
      ["DiamondOre", 45757],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "underground_jungle",
    id: 78,
    oreMultipliers: [
      ["CoalOre", 1188059],
      ["CopperOre", 173213],
      ["IronOre", 177469],
      ["GoldOre", 55380],
      ["DiamondOre", 46659],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "alpha_islands_winter",
    id: 79,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "alpha_islands",
    id: 80,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "alpine_grove",
    id: 81,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "alpine_highlands",
    id: 82,
    oreMultipliers: [
      ["CoalOre", 119229],
      ["CopperOre", 64409],
      ["IronOre", 13800],
      ["GoldOre", 24],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "amethyst_canyon",
    id: 83,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "amethyst_rainforest",
    id: 84,
    oreMultipliers: [
      ["CoalOre", 66788],
      ["CopperOre", 28984],
      ["IronOre", 2889],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "ancient_sands",
    id: 85,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "arid_highlands",
    id: 86,
    oreMultipliers: [
      ["CoalOre", 234757],
      ["CopperOre", 74873],
      ["IronOre", 39135],
      ["GoldOre", 84],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "ashen_savanna",
    id: 87,
    oreMultipliers: [
      ["CoalOre", 18133],
      ["CopperOre", 0],
      ["IronOre", 7054],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 17],
    ],
  },
  {
    name: "basalt_cliffs",
    id: 88,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "birch_taiga",
    id: 89,
    oreMultipliers: [
      ["CoalOre", 8708],
      ["CopperOre", 722],
      ["IronOre", 2568],
      ["GoldOre", 2],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "blooming_plateau",
    id: 90,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "blooming_valley",
    id: 91,
    oreMultipliers: [
      ["CoalOre", 165],
      ["CopperOre", 86],
      ["IronOre", 58],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "brushland",
    id: 92,
    oreMultipliers: [
      ["CoalOre", 413920],
      ["CopperOre", 164927],
      ["IronOre", 86133],
      ["GoldOre", 874],
      ["DiamondOre", 64],
      ["NeptuniumOre", 15],
    ],
  },
  {
    name: "bryce_canyon",
    id: 93,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "caldera",
    id: 94,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "cloud_forest",
    id: 95,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "cold_shrubland",
    id: 96,
    oreMultipliers: [
      ["CoalOre", 81455],
      ["CopperOre", 35975],
      ["IronOre", 8905],
      ["GoldOre", 106],
      ["DiamondOre", 12],
      ["NeptuniumOre", 1],
    ],
  },
  {
    name: "desert_oasis",
    id: 97,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "desert_spires",
    id: 98,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "emerald_peaks",
    id: 99,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "forested_highlands",
    id: 100,
    oreMultipliers: [
      ["CoalOre", 237795],
      ["CopperOre", 97146],
      ["IronOre", 29175],
      ["GoldOre", 32],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "fractured_savanna",
    id: 101,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "frozen_cliffs",
    id: 102,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "glacial_chasm",
    id: 103,
    oreMultipliers: [
      ["CoalOre", 52750],
      ["CopperOre", 21697],
      ["IronOre", 4579],
      ["GoldOre", 66],
      ["DiamondOre", 4],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "granite_cliffs",
    id: 104,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "gravel_beach",
    id: 105,
    oreMultipliers: [
      ["CoalOre", 18221],
      ["CopperOre", 14444],
      ["IronOre", 5236],
      ["GoldOre", 384],
      ["DiamondOre", 22],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "gravel_desert",
    id: 106,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "haze_mountain",
    id: 107,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "highlands",
    id: 108,
    oreMultipliers: [
      ["CoalOre", 145699],
      ["CopperOre", 90692],
      ["IronOre", 16966],
      ["GoldOre", 30],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "hot_shrubland",
    id: 109,
    oreMultipliers: [
      ["CoalOre", 21814],
      ["CopperOre", 7571],
      ["IronOre", 2482],
      ["GoldOre", 34],
      ["DiamondOre", 2],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "ice_marsh",
    id: 110,
    oreMultipliers: [
      ["CoalOre", 20087],
      ["CopperOre", 9800],
      ["IronOre", 4161],
      ["GoldOre", 180],
      ["DiamondOre", 21],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "jungle_mountains",
    id: 111,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "lavender_forest",
    id: 112,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "lavender_valley",
    id: 113,
    oreMultipliers: [
      ["CoalOre", 10894],
      ["CopperOre", 4897],
      ["IronOre", 521],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 2],
    ],
  },
  {
    name: "lush_desert",
    id: 114,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "lush_valley",
    id: 115,
    oreMultipliers: [
      ["CoalOre", 3005],
      ["CopperOre", 1919],
      ["IronOre", 656],
      ["GoldOre", 11],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "mirage_isles",
    id: 116,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "moonlight_grove",
    id: 117,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "moonlight_valley",
    id: 118,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "mountain_steppe",
    id: 119,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "orchid_swamp",
    id: 120,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "painted_mountains",
    id: 121,
    oreMultipliers: [
      ["CoalOre", 111780],
      ["CopperOre", 60],
      ["IronOre", 52729],
      ["GoldOre", 211],
      ["DiamondOre", 0],
      ["NeptuniumOre", 3067],
    ],
  },
  {
    name: "red_oasis",
    id: 122,
    oreMultipliers: [
      ["CoalOre", 436],
      ["CopperOre", 5306],
      ["IronOre", 1365],
      ["GoldOre", 46],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "rocky_jungle",
    id: 123,
    oreMultipliers: [
      ["CoalOre", 166294],
      ["CopperOre", 63442],
      ["IronOre", 7068],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 10],
    ],
  },
  {
    name: "rocky_mountains",
    id: 124,
    oreMultipliers: [
      ["CoalOre", 50559],
      ["CopperOre", 15],
      ["IronOre", 19955],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 1284],
    ],
  },
  {
    name: "rocky_shrubland",
    id: 125,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "sakura_grove",
    id: 126,
    oreMultipliers: [
      ["CoalOre", 3769],
      ["CopperOre", 2136],
      ["IronOre", 336],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "sakura_valley",
    id: 127,
    oreMultipliers: [
      ["CoalOre", 5332],
      ["CopperOre", 3662],
      ["IronOre", 812],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "sandstone_valley",
    id: 128,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "savanna_badlands",
    id: 129,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "savanna_slopes",
    id: 130,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "scarlet_mountains",
    id: 131,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "shield_clearing",
    id: 132,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "shield",
    id: 133,
    oreMultipliers: [
      ["CoalOre", 33],
      ["CopperOre", 10],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 1],
    ],
  },
  {
    name: "shrubland",
    id: 134,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "siberian_grove",
    id: 135,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "siberian_taiga",
    id: 136,
    oreMultipliers: [
      ["CoalOre", 19346],
      ["CopperOre", 8388],
      ["IronOre", 1456],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "skylands_autumn",
    id: 137,
    oreMultipliers: [
      ["CoalOre", 17],
      ["CopperOre", 21],
      ["IronOre", 88],
      ["GoldOre", 86],
      ["DiamondOre", 75],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "skylands_spring",
    id: 138,
    oreMultipliers: [
      ["CoalOre", 548],
      ["CopperOre", 857],
      ["IronOre", 3842],
      ["GoldOre", 2416],
      ["DiamondOre", 1880],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "skylands_summer",
    id: 139,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "skylands_winter",
    id: 140,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "skylands",
    id: 141,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "snowy_badlands",
    id: 142,
    oreMultipliers: [
      ["CoalOre", 511],
      ["CopperOre", 57],
      ["IronOre", 81],
      ["GoldOre", 222],
      ["DiamondOre", 0],
      ["NeptuniumOre", 2],
    ],
  },
  {
    name: "snowy_cherry_grove",
    id: 143,
    oreMultipliers: [
      ["CoalOre", 28414],
      ["CopperOre", 1521],
      ["IronOre", 7796],
      ["GoldOre", 7],
      ["DiamondOre", 0],
      ["NeptuniumOre", 710],
    ],
  },
  {
    name: "snowy_maple_forest",
    id: 144,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "snowy_shield",
    id: 145,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "steppe",
    id: 146,
    oreMultipliers: [
      ["CoalOre", 48251],
      ["CopperOre", 30340],
      ["IronOre", 5903],
      ["GoldOre", 19],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "stony_spires",
    id: 147,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "temperate_highlands",
    id: 148,
    oreMultipliers: [
      ["CoalOre", 56394],
      ["CopperOre", 30594],
      ["IronOre", 7983],
      ["GoldOre", 35],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "tropical_jungle",
    id: 149,
    oreMultipliers: [
      ["CoalOre", 166016],
      ["CopperOre", 84063],
      ["IronOre", 12838],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 6],
    ],
  },
  {
    name: "valley_clearing",
    id: 150,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "volcanic_crater",
    id: 151,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "volcanic_peaks",
    id: 152,
    oreMultipliers: [
      ["CoalOre", 312563],
      ["CopperOre", 65],
      ["IronOre", 2211],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 9711],
    ],
  },
  {
    name: "warm_river",
    id: 153,
    oreMultipliers: [
      ["CoalOre", 91],
      ["CopperOre", 75],
      ["IronOre", 82],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "warped_mesa",
    id: 154,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "white_cliffs",
    id: 155,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "white_mesa",
    id: 156,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "windswept_spires",
    id: 157,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "wintry_forest",
    id: 158,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "wintry_lowlands",
    id: 159,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "yellowstone",
    id: 160,
    oreMultipliers: [
      ["CoalOre", 125109],
      ["CopperOre", 32588],
      ["IronOre", 35424],
      ["GoldOre", 265],
      ["DiamondOre", 0],
      ["NeptuniumOre", 4],
    ],
  },
  {
    name: "yosemite_cliffs",
    id: 161,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
  {
    name: "yosemite_lowlands",
    id: 162,
    oreMultipliers: [
      ["CoalOre", 0],
      ["CopperOre", 0],
      ["IronOre", 0],
      ["GoldOre", 0],
      ["DiamondOre", 0],
      ["NeptuniumOre", 0],
    ],
  },
]);

export const biomesByName = biomes.reduce(
  (acc, biome) => {
    acc[biome.name] = biome;
    return acc;
  },
  {} as Record<BiomeName, BiomeDefinition>,
);

export const biomesById = biomes.reduce(
  (acc, biome) => {
    acc[biome.id] = biome;
    return acc;
  },
  {} as Record<number, BiomeDefinition>,
);
