// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RegionMerkleRoot } from "../src/codegen/tables/RegionMerkleRoot.sol";

function initTerrain() {
  RegionMerkleRoot.set(0, 0, hex"efccfa14a84f91057bc4c3d97956bba90154ba8556a15552a45a385c0c7355a6");
}
