// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RegionMerkleRoot } from "../src/codegen/tables/RegionMerkleRoot.sol";

function initTerrain() {
  RegionMerkleRoot.set(0, 0, hex"08b0af63e4cbdd09fbaf8db60c749114a933b226774c77502f05425c35ba40f5");
}
