// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RegionMerkleRoot } from "../src/codegen/tables/RegionMerkleRoot.sol";

function initTerrain() {
  RegionMerkleRoot.set(0, 0, hex"06806b5f550089b6b8547c56b155b4ddbff95f96bd9c3738fb56395b935410c9");
}
