// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { AccessGroupCount } from "./tables/AccessGroupCount.sol";
import { AccessGroupOwner } from "./tables/AccessGroupOwner.sol";
import { AccessGroupMember } from "./tables/AccessGroupMember.sol";
import { EntityAccessGroup } from "./tables/EntityAccessGroup.sol";
import { TextSignContent } from "./tables/TextSignContent.sol";
