// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { AllowedCaller } from "./tables/AllowedCaller.sol";
import { Owner } from "./tables/Owner.sol";
import { SmartItem } from "./tables/SmartItem.sol";

import { UniqueEntity } from "./tables/UniqueEntity.sol";
