// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { AccessGroupCount } from "./tables/AccessGroupCount.sol";

import { AccessGroupMember } from "./tables/AccessGroupMember.sol";
import { AccessGroupOwner } from "./tables/AccessGroupOwner.sol";

import { ContentURI } from "./tables/ContentURI.sol";
import { EntityAccessGroup } from "./tables/EntityAccessGroup.sol";
