name: Contracts Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  forge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Foundry
        shell: bash
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source "$HOME/.bashrc"
          foundryup

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build

      - name: Run tests in packages/world
        working-directory: packages/world
        run: pnpm run test
